// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.1
// source: proto.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ChitChatService_Introduce_FullMethodName = "/proto.ChitChatService/Introduce"
)

// ChitChatServiceClient is the client API for ChitChatService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ChitChatServiceClient interface {
	Introduce(ctx context.Context, in *Message, opts ...grpc.CallOption) (*Empty, error)
}

type chitChatServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewChitChatServiceClient(cc grpc.ClientConnInterface) ChitChatServiceClient {
	return &chitChatServiceClient{cc}
}

func (c *chitChatServiceClient) Introduce(ctx context.Context, in *Message, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, ChitChatService_Introduce_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ChitChatServiceServer is the server API for ChitChatService service.
// All implementations must embed UnimplementedChitChatServiceServer
// for forward compatibility.
type ChitChatServiceServer interface {
	Introduce(context.Context, *Message) (*Empty, error)
	mustEmbedUnimplementedChitChatServiceServer()
}

// UnimplementedChitChatServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedChitChatServiceServer struct{}

func (UnimplementedChitChatServiceServer) Introduce(context.Context, *Message) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Introduce not implemented")
}
func (UnimplementedChitChatServiceServer) mustEmbedUnimplementedChitChatServiceServer() {}
func (UnimplementedChitChatServiceServer) testEmbeddedByValue()                         {}

// UnsafeChitChatServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ChitChatServiceServer will
// result in compilation errors.
type UnsafeChitChatServiceServer interface {
	mustEmbedUnimplementedChitChatServiceServer()
}

func RegisterChitChatServiceServer(s grpc.ServiceRegistrar, srv ChitChatServiceServer) {
	// If the following call pancis, it indicates UnimplementedChitChatServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ChitChatService_ServiceDesc, srv)
}

func _ChitChatService_Introduce_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Message)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChitChatServiceServer).Introduce(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChitChatService_Introduce_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChitChatServiceServer).Introduce(ctx, req.(*Message))
	}
	return interceptor(ctx, in, info, handler)
}

// ChitChatService_ServiceDesc is the grpc.ServiceDesc for ChitChatService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ChitChatService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.ChitChatService",
	HandlerType: (*ChitChatServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Introduce",
			Handler:    _ChitChatService_Introduce_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto.proto",
}
